const clt = require('./config/client')
clt.load(`${process.cwd()}/commands`, clt.commands)
clt.load(`${process.cwd()}/modules`, clt.buttons)
require('fs').readdirSync('./events').filter(f => f.endsWith('.js'))
  .forEach(file => {
    const evt = require(`./events/${file}`)
    clt[evt.once ? 'once' : 'on'](evt.name, (...args) => evt.execute(...args))
  })
require('dotenv').config()
clt.login(process.env.SOFTundWET)
console.log(clt.commands.toJSON())
