name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Clean install dependencies check formating and build
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 19
      - run: |
          npm install
          npm run lint
          npm run build
